# Generated by Django 2.1.1 on 2018-09-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=20)),
                ('recipient_email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField(verbose_name='Date Received')),
            ],
        ),
    ]
